/** Compare lives under Research so sheet + compare share one workspace URL space */
export const DASHBOARD_PATH = '/'
export const FILES_PATH = '/files'
export const RESEARCH_PATH = '/research'
export const PARTS_CATALOG_PATH = '/parts-catalog'
export const RESEARCH_COMPARE_PATH = '/research/compare'
export const WISHLIST_PATH = '/wishlist'
export const BUCKET_PATH = '/bucket'
export const PURCHASE_ORDER_PATH = '/purchase-order'
export const OEM_PATH = '/oem'
export const OEM_BOM_PATH = '/oem/bom'
export const OEM_OVERVIEW_PATH = '/oem/overview'
export const SUPPLIER_PATH = '/supplier'
export const SUPPLIER_HOME_PATH = '/supplier/home'
export const OEM_PORTAL_PATH = '/oem/portal'
export const COMPARE_NAV_SESSION_KEY = 'ir-compare-nav-source'
